name: build-docker-containers

on:
  # the 1st condition
  workflow_run:
    workflows: ["Testing"]
    branches: [main]
    types:
      - completed

jobs:

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
