name: Node.js CI

on: [push]

jobs:
  Tes:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}


    - run: npm install
      working-directory: ./client

    - run: npm ci
      working-directory: ./client

    - run: npm run-script build
      working-directory: ./client

    - run: npm test
      working-directory: ./client
